use mscomputers_ventas;

INSERT INTO TIPO_DOCUMENTO (COD_TIPO_DOCUMENTO, NOMBRE) 
VALUES ('TD0001', 'DNI' );

INSERT INTO TIPO_DOCUMENTO (COD_TIPO_DOCUMENTO, NOMBRE) 
VALUES ('TD0002', 'RUC' );

INSERT INTO METODO_PAGO (COD_METODO_PAGO, NOMBRE) 
VALUES ('MP0001', 'EFECTIVO' );

INSERT INTO METODO_PAGO (COD_METODO_PAGO, NOMBRE) 
VALUES ('MP0002', 'TRANSFERENCIA' );

INSERT INTO METODO_PAGO (COD_METODO_PAGO, NOMBRE) 
VALUES ('MP0003', 'YAPE/PLIN' );

INSERT INTO distrito (cod_distrito, nombre) VALUES
('D002', 'Santa Anita'),
('D003', 'Ate'),
('D004', 'San Juan de Lurigancho');